name = "Perpendicular"
author = "Diamondback88"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c831599b6dda739b73e522f0e1936be4c4378d752febf44321dc581619ed504"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
