name = "Perpendicular"
author = "Diamondback88"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cf7b93639790b469abf21f83e4ec8c0a8afb66610986792dda5ed1913c58c52"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
