name = "Perpendicular"
author = "Diamondback88"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bee3aab76b73071c861c5f19ac475d8e3961f277dfb771e8ee7a78e29b87255"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
