name = "Perpendicular"
author = "Diamondback88"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71d61e2ffe0d88cb2b9dde38298c8408b331b426fb7e7ca1f70267de79e90bd7"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
