name = "Perpendicular"
author = "Diamondback88"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f06ef83662719c826b8e3c0b9518ac4ba4cd7c211e735bc92d91f5e0028294c"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
