name = "Perpendicular"
author = "Diamondback88"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d3d11d403f604d62fe6392b72d4a5595d006000893a2840f24988ed1a8963f8"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
