name = "Perpendicular"
author = "Diamondback88"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b8e30c21c8e78d265ee3c733daad49c771501b1bf7198a3f283e5a0ff8c413e"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
