name = "Perpendicular"
author = "Diamondback88"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d89067e424dc25a6047bba01610daf53eb7051e08b17fd66e6db459346713302"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
