name = "Perpendicular"
author = "Diamondback88"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "066400825b24ae01a0aabe994b289240399599240427f67b501c92149ca2b890"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
