blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://discord.parallelmc.org
    about: General questions and support for Perpendicular are provided on the ParallelMC Discord server!
