name: Mod Request
description: Request a mod to be added to Perpendicular.
labels: mod request
body:
- type: markdown
  attributes:
    value: |
      Before requesting a mod, [please search](https://github.com/ParallelMC/Perpendicular/issues) to make sure it hasn't already been requested. 

- type: input
  attributes:
    label: Link to Mod
    description: Use a CurseForge link if the mod has one. Otherwise, paste the non-CurseForge link.
    placeholder: Paste the link to the mod here.
  validations:
    required: true

- type: textarea
  attributes:
    label: What does the mod do?
    description: Give us a short description of the mod's features.
  validations:
    required: true     

- type: textarea
  attributes:
    label: Why should the mod be added?
    description: Make sure the mod doesn't overlap too much with an existing mod in the pack!
  validations:
    required: true 

- type: textarea
  attributes:
    label: Additional Details
    description: Anything else you want to add?
  validations:
    required: false      
