name = "Perpendicular"
author = "Diamondback88"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d1cff5fbddb80c4279f069e41a7aaa76a319cdd11b9414772fb7473225f795f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
