name = "Perpendicular"
author = "Diamondback88"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65c20c436fba9ca999f2c45e394f9d87741bd09432cc2a4652a6217e0588af13"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
