name = "Perpendicular"
author = "Diamondback88"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "461faaf0143184ab3835f6cedd6d49f29c1bc0e80f8da434445a46657fb3f597"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
