name = "Perpendicular"
author = "Diamondback88"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85bda08754343066c582ddd02c257105a6840b110f4b42313d162dc3aec0df0d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
