name = "Perpendicular"
author = "Diamondback88"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "160fa0f543945f9bb1e5bc9d649d9f0d37be6c635af85ebbceeba20184009c49"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
