name = "Perpendicular"
author = "Diamondback88"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "489abc4312931b52aab61b58e7c0900ae8210dfa400c77a2309193805f49650c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
