name = "Perpendicular"
author = "Diamondback88"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "121cf53ef7c26b214f58e754a4e73100058f5f6a867cb37b85d78e1437500434"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
