name = "Perpendicular"
author = "Diamondback88"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7a4662cd1bff33023f3a7649b4a9e7db755efbb08e506fad0011a9510112201"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
